# Importing necessary libraries

In [1]:
import torch
import numpy as np

# Tensor Basics

## Initializing a tensor

### Creating a tensor directly from data

In [7]:
data = [ [1, 2], [3, 4] ]
x_data = torch.tensor(data)

In [9]:
x_data

tensor([[1, 2],
        [3, 4]])


### Creating a tensor from a NumPy array

In [8]:
np_array = np.array(data) # Taken from previous cell
x_np = torch.from_numpy(np_array)

In [10]:
x_np

tensor([[1, 2],
        [3, 4]])

### Creating a tensor from another tensor

Tensors created from other tensors retain the **shape** and **datatype** of tha original tensor, unless explicity overridden

In [11]:
x_ones = torch.ones_like(x_data) # Retains the properties of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float) # Override the datatype of x_data using 'dtype' arg

In [12]:
x_ones

tensor([[1, 1],
        [1, 1]])

In [13]:
x_rand

tensor([[0.5252, 0.3421],
        [0.8477, 0.4756]])

### Creating a tensor from random or constant values

**shape** is a tuple of tensor dimensions and determines the dimensionality of tensors in some functions

In [26]:
shape = (2, 3,) # Common practice to include trailing commas to make editing easier
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [27]:
rand_tensor

tensor([[0.8527, 0.1707, 0.2751],
        [0.7248, 0.1385, 0.7052]])

In [28]:
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [29]:
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## Attributes of a Tensor

Tensor attributes are:
- shape
- datatype
- device (on which they are stored)

In [30]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Tensor Operations

There are over [1200 operations](https://docs.pytorch.org/docs/stable/torch.html) one can perform on Tensors.

By default, tensors are created on the CPU. Copying large tensors across devices can be expensive in terms of time and memory, but can be done using .to() after checking for accelerator availability using torch.accelerator.is_available()

## Standard operations (indexing, slicing, etc.)

In [34]:
tensor = torch.rand(4, 4)
tensor

tensor([[0.5097, 0.4606, 0.9900, 0.1226],
        [0.0978, 0.2952, 0.8436, 0.6725],
        [0.9641, 0.5846, 0.8267, 0.5915],
        [0.2272, 0.8416, 0.2059, 0.7711]])

In [ ]:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}") # ... is used to represent all remaining dimensions

# Modifying an entire column's values
tensor[:, 1] = 3 # We modify the first column across all the rows
tensor

First row: tensor([0.5097, 0.4606, 0.9900, 0.1226])
First column: tensor([0.5097, 0.0978, 0.9641, 0.2272])
Last column: tensor([0.1226, 0.6725, 0.5915, 0.7711])


tensor([[0.5097, 3.0000, 0.9900, 0.1226],
        [0.0978, 3.0000, 0.8436, 0.6725],
        [0.9641, 3.0000, 0.8267, 0.5915],
        [0.2272, 3.0000, 0.2059, 0.7711]])

In [71]:
# A little more about '...'
shape = (3, 3, 3, )
n_tensor = torch.rand(shape)
print(n_tensor.shape)
n_tensor

torch.Size([3, 3, 3])


tensor([[[0.1455, 0.1241, 0.9978],
         [0.5764, 0.5939, 0.0195],
         [0.0198, 0.7018, 0.3710]],

        [[0.6321, 0.3949, 0.7210],
         [0.2410, 0.2942, 0.7565],
         [0.9215, 0.8328, 0.2967]],

        [[0.5821, 0.1368, 0.1275],
         [0.3626, 0.4411, 0.9740],
         [0.3256, 0.3238, 0.8430]]])

In [78]:
print(f"First row across the entire tensor:\n\n {n_tensor[:, 0, :]}")
print(f"\n\nThe first layer of the tensor:\n\n {n_tensor[0, :, :]}")

First row across the entire tensor:

 tensor([[0.1455, 0.1241, 0.9978],
        [0.6321, 0.3949, 0.7210],
        [0.5821, 0.1368, 0.1275]])


The first layer of the tensor:

 tensor([[0.1455, 0.1241, 0.9978],
        [0.5764, 0.5939, 0.0195],
        [0.0198, 0.7018, 0.3710]])


We can simplify the retrieval of the first layer of the tensor by using '...'

This currently doesn't seem like it's doing much, but when you're working with n-dimnensional tensors then retrieving the first layer (or the first of anything) would be a tedious process if you had to manually enter ':' for each one

In [75]:
n_tensor[0, ...] # This returns the same thing as n_tensor[0, :, :]

tensor([[0.1455, 0.1241, 0.9978],
        [0.5764, 0.5939, 0.0195],
        [0.0198, 0.7018, 0.3710]])

### Joining Tensors

In [79]:
tensor

tensor([[0.5097, 3.0000, 0.9900, 0.1226],
        [0.0978, 3.0000, 0.8436, 0.6725],
        [0.9641, 3.0000, 0.8267, 0.5915],
        [0.2272, 3.0000, 0.2059, 0.7711]])

In [80]:
cc_tensor = torch.cat([tensor, tensor])
cc_tensor

tensor([[0.5097, 3.0000, 0.9900, 0.1226],
        [0.0978, 3.0000, 0.8436, 0.6725],
        [0.9641, 3.0000, 0.8267, 0.5915],
        [0.2272, 3.0000, 0.2059, 0.7711],
        [0.5097, 3.0000, 0.9900, 0.1226],
        [0.0978, 3.0000, 0.8436, 0.6725],
        [0.9641, 3.0000, 0.8267, 0.5915],
        [0.2272, 3.0000, 0.2059, 0.7711]])

By default we join tensors by the 0th dimension (we append the next tensor row-wise in case of 2D tensors). We can change the dimension by specifying the 'dim' arg.

In [81]:
cc_dim_tensor = torch.cat([tensor, tensor], dim=1)
cc_dim_tensor

tensor([[0.5097, 3.0000, 0.9900, 0.1226, 0.5097, 3.0000, 0.9900, 0.1226],
        [0.0978, 3.0000, 0.8436, 0.6725, 0.0978, 3.0000, 0.8436, 0.6725],
        [0.9641, 3.0000, 0.8267, 0.5915, 0.9641, 3.0000, 0.8267, 0.5915],
        [0.2272, 3.0000, 0.2059, 0.7711, 0.2272, 3.0000, 0.2059, 0.7711]])

torch.cat() applies along *existing* dimensions.

torch.stack() applies along a *new* dimension.

In [ ]:
s_tensor = torch.stack([tensor, tensor]) # This adds a new "depth" dimension to our 2D matrix and makes it a 3D matrix
s_tensor

tensor([[[0.5097, 3.0000, 0.9900, 0.1226],
         [0.0978, 3.0000, 0.8436, 0.6725],
         [0.9641, 3.0000, 0.8267, 0.5915],
         [0.2272, 3.0000, 0.2059, 0.7711]],

        [[0.5097, 3.0000, 0.9900, 0.1226],
         [0.0978, 3.0000, 0.8436, 0.6725],
         [0.9641, 3.0000, 0.8267, 0.5915],
         [0.2272, 3.0000, 0.2059, 0.7711]]])

The 'dim' arg applies to stack as well and determines the way in which the cards are stacked

In [83]:
s1_tensor = torch.stack([tensor, tensor], dim=1)
s1_tensor

tensor([[[0.5097, 3.0000, 0.9900, 0.1226],
         [0.5097, 3.0000, 0.9900, 0.1226]],

        [[0.0978, 3.0000, 0.8436, 0.6725],
         [0.0978, 3.0000, 0.8436, 0.6725]],

        [[0.9641, 3.0000, 0.8267, 0.5915],
         [0.9641, 3.0000, 0.8267, 0.5915]],

        [[0.2272, 3.0000, 0.2059, 0.7711],
         [0.2272, 3.0000, 0.2059, 0.7711]]])

In [84]:
s2_tensor = torch.stack([tensor, tensor], dim=2)
s2_tensor

tensor([[[0.5097, 0.5097],
         [3.0000, 3.0000],
         [0.9900, 0.9900],
         [0.1226, 0.1226]],

        [[0.0978, 0.0978],
         [3.0000, 3.0000],
         [0.8436, 0.8436],
         [0.6725, 0.6725]],

        [[0.9641, 0.9641],
         [3.0000, 3.0000],
         [0.8267, 0.8267],
         [0.5915, 0.5915]],

        [[0.2272, 0.2272],
         [3.0000, 3.0000],
         [0.2059, 0.2059],
         [0.7711, 0.7711]]])

A simple way to visualize how they would be stacked is to take 2 index cards and:

dim=0 : Place both flat on top of each other and look at the top-down view to identify the layers

dim=1 : Place both cards standing and side-by-side along the width and look at the top-down view. Take the top half of the index cards as the first layer, and the bottom half as the second layer

dim=2 : Similar to dim=1, but place it along the height now and do the same

Note that if you do dim=-1 then it would just be the last dimension (in our case dim=2)

In [85]:
slast_tensor = torch.stack([tensor, tensor], dim=-1)
slast_tensor

tensor([[[0.5097, 0.5097],
         [3.0000, 3.0000],
         [0.9900, 0.9900],
         [0.1226, 0.1226]],

        [[0.0978, 0.0978],
         [3.0000, 3.0000],
         [0.8436, 0.8436],
         [0.6725, 0.6725]],

        [[0.9641, 0.9641],
         [3.0000, 3.0000],
         [0.8267, 0.8267],
         [0.5915, 0.5915]],

        [[0.2272, 0.2272],
         [3.0000, 3.0000],
         [0.2059, 0.2059],
         [0.7711, 0.7711]]])